-- OPTIONAL: only if you use Supabase for other features (social/shipping).
-- Deposit approvals no longer require Supabase — they use Upstash Redis or in-memory.
--
-- If you already use montana_settings and want deposits platform allowed:
-- ALTER TABLE montana_settings DROP CONSTRAINT IF EXISTS montana_settings_platform_check;
-- ALTER TABLE montana_settings ADD CONSTRAINT montana_settings_platform_check
--   CHECK (platform IN ('facebook', 'instagram', 'shipping', 'deposits'));
