-- Full IMS doctor list import
-- Source: Dr List - Bani Suief & Fayoum (Amira Nabil).xlsx
-- Doctors: 5275
-- Requires: 018_crm_ims_bricks_seed.sql
-- Run parts 020_* in order (part 01 runs cleanup)

alter table crm_doctors add column if not exists doctor_type text default 'doctor';

-- Part 14/14 · 75 rows

insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'احمد خطاب', 'الباجور ش بنها بجوار المدرسة الثانوية', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB1', 'Pedia', true, 'IMS Dr List import · M 1_Menofia' from crm_bricks b where b.name ilike '%Menofia 4%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'احمد قناوي', 'شبين الكوم', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB1', 'Pedia', true, 'IMS Dr List import · M 1_Menofia' from crm_bricks b where b.name ilike '%Menofia 4%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'بهاء بدوي', 'شبين الكوم', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB1', 'Pedia', true, 'IMS Dr List import · M 1_Menofia' from crm_bricks b where b.name ilike '%Menofia 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'محمود ابوالخير', 'قويسنا', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB1', 'Pedia', true, 'IMS Dr List import · M 1_Menofia' from crm_bricks b where b.name ilike '%Menofia 2%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'ايه الجرواني', 'مركز الور ئشارع باريس شبين الكوم', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 1_Menofia' from crm_bricks b where b.name ilike '%Menofia 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'مارينا صلاح', 'مركز الور شارع باريس', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 1_Menofia' from crm_bricks b where b.name ilike '%Menofia 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'سحر ربيع', null, null, b.id, 'HCO CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 1_Menofia' from crm_bricks b where b.name ilike '%Menofia 2%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'اشراق علام', null, null, b.id, 'HCO CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 1_Menofia' from crm_bricks b where b.name ilike '%Menofia 4%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'هدير سليم', null, null, b.id, 'HCO CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 1_Menofia' from crm_bricks b where b.name ilike '%Menofia 3%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'مركز القصر الملكي - شبين الكوم', 'شارع جمال عبدالناصرمركز سباركل - دلتا ماركت - شبين الكوم', null, b.id, 'POLYCLINIC', 'polyclinic', 'AB2', 'Null', true, 'IMS Dr List import · M 1_Menofia' from crm_bricks b where b.name ilike '%Menofia 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'عصمت محممد', null, null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 1_Menofia' from crm_bricks b where b.name ilike '%Menofia 2%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'مركز EMA - المنوفيه', null, null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 1_Menofia' from crm_bricks b where b.name ilike '%Menofia 3%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'مصطفي شاهين', 'عماره فوش كوبري ميدان حارث - ميدان حارث - صيدليه محب - بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 17' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'منال جرجس', 'برج الشيماء - شارع بورسعيد ارض الحريه - صيدليه ابوسيف - بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 18' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'منال عبدالستار', 'سعد زعلول - امام صيدليه الشفا - الواسطي بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 19' from crm_bricks b where b.name ilike '%Bani Suif 2%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'مصطفي ياسين', 'الاباصيري خلف محل ريلاكس بجانب مدرسه الحديثه - صيدليه عمرو الروبي خلف محلف ريلاكس للملابس الاباصيري - بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 20' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'اماني طه', 'ناصيه شارع السنترالشارع الممر بجوار صيدليه التعاونيه - صيدله التعاونيه امام شارع السنترال - الفيوم سنتر', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 21' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'اماني غريب', 'دحدوره هدي اعلي محل الخديوي - الدحدوره - الفيوم سنتر', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 22' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'اماني يعقوب', 'شارع السنترال اعلي استوديو وهيب بجانب بن زمان - بن زمان استوديو وهيب - الفيوم سنتر', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 23' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'امل رؤوف', 'برج امام المسله - المسله - صيدليه جيمي - الفيوم سنتر', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 24' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'ايه عماد صادق', 'برج الجوهره الطبي - شارع احمد عرابي - صيدليه حسام احمد - الواسطه بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 25' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'ايه عبدالحميد', 'احمد عرابي الزراعين - صيدليه الاسعاف - مستشفي الزهراء المبني الاداري - بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 26' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'بسمه حماده', 'بجانب الكوبري العلوي المسله - قريب من موقف مصر وسنورس - موقف سنورس - الفيوم سنتر', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 27' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'بسمه نورالدين', 'برج بجانب سوبر ماركت بابا عبد - ميدان رفعت عزمي - صيدليه الجلاء - الفيوم سنتر', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 28' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'بكينام ابوالمكارم', 'برج الاطباء - ارض الحريه - صيدليه فريد عكاشه ارض الحريه - بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 29' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'ايمان يحي', 'برج الصديق - ببا الناحيه التانيه من موقف بني سويف - صيدليه شبل وصيدليه مؤمن - ببا بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 30' from crm_bricks b where b.name ilike '%Bani Suif 3%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'ايمان سمير', 'برج الحياه - شارع بورسعيد ارض الحريه - صيدليه العزبي - معرض شباب مصر - بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 31' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'ابتسام زارع', 'برج المنار - شارع الكوبري - صيدليه محمود محمد ابراهيم - الكوبري العلوي - الواسطه بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 32' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'ابتهال سيد', 'قريب من منطقه الفواريقه اعلي صيدليه محمد مرسي - صيدليه محمد مرسي - ببا بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 33' from crm_bricks b where b.name ilike '%Bani Suif 3%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'احمد ابوسيف', 'شارع احمد عرابي برج الاطباء امام المحكمه - المحكمه - الواسطي بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 34' from crm_bricks b where b.name ilike '%Bani Suif 2%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'احمد نجاتي', 'برج اليسر - شارع صلاح سالم - كليه السياحه والفنادق - بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 35' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'سوزان عريان', 'شارع احمد عرابي قريب من مستشفي الزهراء - مستشفي السلام - بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 36' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'ساره الناظر', 'برج امام اولاد رجب - ارض الحريه - اولاد رجب - بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 37' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'ساره محمد عادل', 'برج الاطباء ارض الحريه - ارض الحريه - صيدليه فريد عكاشه - بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 38' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'طلال عبدالرحيم', 'الفيوم شارع المحمد فوق صيدليه وصفه', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 39' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'عبدالحميد فضل', 'Bani Suif 1', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 40' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'شيماء طه', 'برج حديث المدينه - شارع صلاح سالم - بنك اسكندريه - بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 41' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'صفاء الجندي', 'برج الصديق - الجانب الاخر من موقف بني سويفف ببا - برج الصديق بجوار صيدليه شب - ببا بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 42' from crm_bricks b where b.name ilike '%Bani Suif 3%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'حنان عبدالرزاق', 'برج مطعم ماكدونالدز - عبدالسلام عارف - مطعم ماكدونالدز - بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 43' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'حنان مصطفي', 'برج الحياه - شارع معرض شباب مصر - صيدليه العزبي معرض شباب مصر - بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 44' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'جوزيف عطيه', 'عماره صيدليه التعاونيه - امام شارع السنترال - صيدليه التعاونيه بجوار سيفورا - الفيوم سنتر', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 45' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'رشا الهاين', 'خلف مبني we - مصطفي باشا - صيدليه الباشا - الفيوم سنتر', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 46' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'رحاب محمد نجيب', 'برج زيزينيا - شارع بورسعيد ارض الحريه - بنك التنميه والائتمان الزراعي - بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 47' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'ريم علي', 'برج امام قصر الثقافه - شارع البحر - قصر الثقافه مخبز المدينه المنوره - بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 48' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'ريمون بشري', 'برج امام بنك اسكندريه - ميدان المديريه بنك اسكندريه - صيدليه الامراء - بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 49' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'داليا صفوت', 'برج الاطباء مركز دايموند - ارض الحريه - صيدليه فريد عكاشه', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 50' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'رانيا رحيم', 'ميدان الفنيه - امام صيدليه هدي خليفه - الفيوم سنتر', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 51' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'مستشفي السلام - بني سويف', 'بني سويف', null, b.id, 'POLYCLINIC', 'polyclinic', 'BB2', 'Null', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 52' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'عبدالله فوزي', 'بني سويف - الفيوم', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Null', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 53' from crm_bricks b where b.name ilike '%Bani Suif 3%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'سوزي مرقص', 'السلام - مستشفي السلام - بني سويف', null, b.id, 'HCO CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 54' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'المركز الطبي الحادقه - الفيوم', 'بندر الفيوم - صيدليه جيما - الفيوم', null, b.id, 'HEALTH CARE UNIT', 'doctor', 'AB2', 'Null', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 55' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'مستشفي بني سويف الجامعي - بني سويف', 'مقبل - بجوار كليه الطب البيطري - بني سويف', null, b.id, 'UNIVERSITY HOSPITAL', 'hospital', 'AB2', 'Null', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 56' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'مستشفي الجلديه بني سويف - بني سويف', 'شارع الروضه - بجوار مطحن بني سويف - بني سويف', null, b.id, 'MOH', 'doctor', 'AB2', 'Null', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 57' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'مستشفي بني سويف العام - بني سويف', 'كورنيش النيل - امام شرطه المسطحات - بني سويف', null, b.id, 'MOH', 'doctor', 'AB2', 'Null', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 58' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'مستشفي الفيوم العام - الفيوم', 'النبوي المهندس - المسله - الفيوم', null, b.id, 'MOH', 'doctor', 'AB2', 'Null', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 59' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'مستشفي الجلديه الفيوم - الفيوم', 'ملف الصدر - بجوار م التامين الصحي - الفيوم', null, b.id, 'MOH', 'doctor', 'AB2', 'Null', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 60' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'مستشفي الفيوم الجامعي - الفيوم', 'مصطفي حسن - خلف عماره التامينات - الفيوم', null, b.id, 'UNIVERSITY HOSPITAL', 'hospital', 'BB2', 'Null', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 61' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'دعاء عبدالقادر', 'عيادات روح الحياه - شارع مول البهاء - مول البهاء - الواسطه بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 62' from crm_bricks b where b.name ilike '%Bani Suif 2%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'ناريمان كمال', 'برج امام صيدليه حسام احمد - شارع صيدليه حسام احمد - صيدليه حسام احمد - الواسطه بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 63' from crm_bricks b where b.name ilike '%Bani Suif 2%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'محمد رجب', 'برج زيزينيا - شارع بورسعيد ارض الحريه - بنك التنميه والائتمان الزراعي - بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 64' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'اسامه نبيل', 'مركز you ف المسله الفيوم', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 65' from crm_bricks b where b.name ilike '%Fayoum 2%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'دينا هلال', 'بني سويف', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 66' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'اشرف عبدالوهاب', 'Bani Suif 1', null, b.id, 'PRIVATE CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 67' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'نورهان احمد', 'الفيوم', null, b.id, 'HCO CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 68' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'خديجه مجاهد', 'الفيوم', null, b.id, 'HCO CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 69' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'نورهان صبحي', 'الفيوم', null, b.id, 'HCO CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 70' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'ابتسام احمد', 'الفيوم', null, b.id, 'HCO CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 71' from crm_bricks b where b.name ilike '%Bani Suif 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'ساره مجدي', 'الفيوم', null, b.id, 'HCO CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 72' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'اسماء مختار', 'الفيوم', null, b.id, 'HCO CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 73' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'نهال اسامه', 'الفيوم', null, b.id, 'HCO CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 74' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'جهاد حنبولي', 'الفيوم', null, b.id, 'HCO CLINIC', 'doctor', 'BB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 75' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'شيرين عادل', 'الفيوم', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 76' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'شيرين مكرم', 'الفيوم', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 77' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'نهي باتع الروبي', 'الفيوم', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 78' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;
insert into crm_doctors (name, address, phone, brick_id, org_type, doctor_type, class, specialty, approved, notes) select 'مني عبدالجيد', 'الفيوم', null, b.id, 'PRIVATE CLINIC', 'doctor', 'AB2', 'Derma', true, 'IMS Dr List import · M 6_Bani Suef - Fayoum · 79' from crm_bricks b where b.name ilike '%Fayoum 1%' limit 1;

-- end part 14